export { DebateEngine, EngineError, ExternalEditError, computeIdentity, checkMarkdown, normalizeSpec } from "./core/engine.js";
export { loadConfig, saveConfig, createRegistry, DEFAULT_CONFIG, DEFAULT_MODELS, FAKE_MODELS, fakeParticipants, type AppConfig, type ModelDefaults } from "./core/config.js";
export { Registry } from "./core/adapters/registry.js";
export { FakeAdapter, type FakeBehavior } from "./core/adapters/fake.js";
export { ClaudeAdapter } from "./core/adapters/claude.js";
export { CodexAdapter } from "./core/adapters/codex.js";
export { GeminiAdapter } from "./core/adapters/gemini.js";
export { OpenAICompatAdapter, KimiAdapter } from "./core/adapters/openai-compat.js";
export { AnthropicAdapter } from "./core/adapters/anthropic.js";
export { ReplicateAdapter } from "./core/adapters/replicate.js";
export type { Adapter, AdapterRegistry, TurnRequest, TurnResult } from "./core/adapters/types.js";
export { ACTA_SCHEMA, validateActa, renderActa } from "./core/schema.js";
export { PROVIDERS, getProvider, ACCESS_LABEL, type ProviderDef } from "./core/providers.js";
export { CATALOG, getCatalogModel, resolveSpecRef, specFromOffering, specRef, offeringKey, type CatalogModel, type Offering } from "./core/catalog.js";
export * from "./core/secrets.js";
export * from "./core/types.js";
export * as prompts from "./core/prompts.js";
